@echo off
set /p entryName="Enter entry name (You can NOT use HTML formatting.): "
if exist "Entries\%entryName%\" (
  echo Entry already exists! Exiting
  pause
  exit /b 1
) else (
  echo No
)
set /p entryContents="Enter contents of entry (You can use HTML formatting!): "
mkdir "Entries\%entryName%"
cd Entries
cd "%entryName%"
set "file=entry.html"
echo|set /p="<!DOCTYPE html>" > %file%
echo|set /p="<!-- Hello! this file was generated by addEntry.bat -->" >> %file%
echo|set /p="<html>" >> %file%
echo|set /p="<head>" >> %file%
echo|set /p="<title>Entry: %entryName%</title>" >> %file%
echo|set /p="</head>" >> %file%
echo|set /p="<body>" >> %file%
echo|set /p="<h1>%entryName%</h1>" >> %file%
echo|set /p="<br>" >> %file%
echo|set /p="<p>%entryContents%</p>" >> %file%
exit /b 0